# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SERIAL_Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 512)
        MainWindow.setMinimumSize(QtCore.QSize(790, 512))
        MainWindow.setStyleSheet("background-color: rgb(23,23,23);\n"
"color:#DCDCDC;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QToolTip { \n"
"       background-color: rgb(50,50,50); \n"
"       color: white; \n"
"       border: black solid 1px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 7, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(520, 230))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(50, 190, 166);\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_terminal_view = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_terminal_view.setToolTip("")
        self.textBrowser_terminal_view.setStyleSheet("QTextBrowser{\n"
"    border: None;\n"
"    background-color: transparent;\n"
"    font-size: 18px;\n"
"}")
        self.textBrowser_terminal_view.setObjectName("textBrowser_terminal_view")
        self.verticalLayout_4.addWidget(self.textBrowser_terminal_view)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    border: none;\n"
"    font: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_data = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_data.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_data.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_data.setStyleSheet("QLineEdit{\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(50, 190, 166);\n"
"    font-size: 18px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.horizontalLayout_3.addWidget(self.lineEdit_data)
        self.pushButton_send = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_send.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_send.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_send.setToolTipDuration(5000)
        self.pushButton_send.setStyleSheet("QPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    image: url(:/icons/icons8-lleno-enviado-25.png);\n"
"    background-color: rgb(50, 190, 166);\n"
"    border: 1px solid rgb(50, 190, 166);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 175, 155);\n"
"}")
        self.pushButton_send.setText("")
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_3.addWidget(self.pushButton_send)
        self.pushButton_clean = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_clean.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_clean.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clean.setToolTipDuration(5000)
        self.pushButton_clean.setStyleSheet("QPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    image: url(:/icons/icons8-eliminar-25.png);\n"
"    background-color: rgb(50, 190, 166);\n"
"    border: 1px solid rgb(50, 190, 166);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 175, 155);\n"
"}")
        self.pushButton_clean.setText("")
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.horizontalLayout_3.addWidget(self.pushButton_clean)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 184))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setMinimumSize(QtCore.QSize(160, 160))
        self.frame_9.setMaximumSize(QtCore.QSize(160, 160))
        self.frame_9.setStyleSheet("QFrame{\n"
"    border-radius: 80px;\n"
"    background-color: rgb(50, 190, 166);\n"
"    image: url(:/img/settings_10.png);\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_port_list = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_port_list.setMinimumSize(QtCore.QSize(124, 35))
        self.comboBox_port_list.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBox_port_list.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: rgb(50, 190, 166);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_port_list.setObjectName("comboBox_port_list")
        self.horizontalLayout_2.addWidget(self.comboBox_port_list)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_baudrate.setMinimumSize(QtCore.QSize(124, 35))
        self.comboBox_baudrate.setMaximumSize(QtCore.QSize(16777215, 35))
        self.comboBox_baudrate.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: rgb(50, 190, 166);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.horizontalLayout_5.addWidget(self.comboBox_baudrate)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.pushButton_connect = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_connect.setStyleSheet("QPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    \n"
"    background-color: rgb(50, 190, 166);\n"
"    color: white;\n"
"    border: 1px solid rgb(50, 190, 166);\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 175, 155);\n"
"}")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout_5.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_disconnect.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_disconnect.setStyleSheet("QPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    \n"
"    background-color: rgb(50, 190, 166);\n"
"    color: white;\n"
"    border: 1px solid rgb(50, 190, 166);\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 175, 155);\n"
"}")
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout_5.addWidget(self.pushButton_disconnect)
        self.pushButton_refresh = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_refresh.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_refresh.setMaximumSize(QtCore.QSize(16777215, 35))
        self.pushButton_refresh.setStyleSheet("QPushButton{\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    background-color: transparent;\n"
"    color: rgb(50, 190, 166);\n"
"    border: 2px solid rgb(50, 190, 166);\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 175, 155);\n"
"    color: white;\n"
"}")
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout_5.addWidget(self.pushButton_refresh)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SERIAL Terminal"))
        self.lineEdit_data.setPlaceholderText(_translate("MainWindow", "INSERT DATA HERE"))
        self.pushButton_send.setToolTip(_translate("MainWindow", "Send data"))
        self.pushButton_clean.setToolTip(_translate("MainWindow", "Clean Terminal."))
        self.label.setText(_translate("MainWindow", "SETTINGS"))
        self.label_2.setText(_translate("MainWindow", "PORT NAME:"))
        self.label_3.setText(_translate("MainWindow", "BAUDRATE:"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "DISCONNECT"))
        self.pushButton_refresh.setText(_translate("MainWindow", "REFRESH PORT LIST"))
        self.label_4.setText(_translate("MainWindow", "Created by <strong>Allione Joaquín</strong>"))
import resources_rc
